# Generated by Django 4.2.3 on 2023-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productdescription', models.CharField(max_length=200)),
                ('productcategory', models.CharField(max_length=200)),
                ('offerprice', models.CharField(max_length=200)),
                ('actualprice', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=100)),
                ('productimage', models.ImageField(upload_to='productimages')),
            ],
            options={
                'db_table': 'Addproduct',
            },
        ),
        migrations.DeleteModel(
            name='AddItem',
        ),
    ]
