# Generated by Django 4.2.3 on 2023-08-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addproduct_delete_additem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Bag',
            },
        ),
    ]
