# Generated by Django 4.2.3 on 2023-08-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bag',
            table='bag',
        ),
    ]
