# Generated by Django 4.2.3 on 2023-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_bag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='total_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
