# Generated by Django 4.2.3 on 2023-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
